#!/usr/bin/env bash

# Open a wofi menu with power settings
if [ "$1" = "menu" ]; then
    op=$( echo -e " Poweroff\n Reboot\n Suspend" | wofi -i --dmenu | awk '{print tolower($2)}' )

    case $op in 
        poweroff)
                ;&
        reboot)
                ;&
        suspend)
                systemctl $op
                ;;
    esac
fi